id: AEB4E9DD9
title: 'Bestowing the Splendour of All That is Desirable: Fire Offering for the ''Neck-Pouch
  Dagger’ (Purba Gulkhukma) Cycle'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:41:36.367036
  last_modified_at: 2022-03-01 03:41:36.367043
