id: AEB4E9DD9
title: 'Bright Light of the Sun: A Simple Fire Offering Based on a Single Substance'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:41:36.368621
  last_modified_at: 2022-03-01 03:41:36.368625
