id: AEB4E9DD9
title: 'The Treasury of the Four Activities: A Fire Offering to Yumka'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:41:36.371559
  last_modified_at: 2022-03-01 03:41:36.371562
